/**
 * Build. Deliberately ~100 lines of esbuild rather than a framework.
 *
 * For this extension the manifest IS the security-critical surface — the DNR
 * rule permissions, the host permissions, the content-script match patterns —
 * so it stays hand-written and readable rather than being generated by a tool
 * that puts an abstraction between the author and the most sensitive file here.
 */

import * as esbuild from 'esbuild';
import { copyFileSync, mkdirSync, rmSync, existsSync, readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { writeIcons } from './tools/make-icons.mjs';

const root = dirname(fileURLToPath(import.meta.url));
const src = join(root, 'src');
const dist = join(root, 'dist');

const watch = process.argv.includes('--watch');
const dev = watch || process.argv.includes('--dev');

/** Content scripts are classic scripts and cannot use ES module imports, so
 *  everything is bundled to IIFE. Output is flat, which keeps
 *  web_accessible_resources and manifest paths trivial to read. */
const ENTRIES = {
  sw: join(src, 'background/sw.ts'),
  'host-overlay': join(src, 'content/host-overlay.ts'),
  'tenor-frame': join(src, 'content/tenor-frame.ts'),
  picker: join(src, 'picker/picker.ts'),
  offscreen: join(src, 'offscreen/offscreen.ts'),
};

const STATIC_FILES = [
  ['manifest.json', 'manifest.json'],
  ['content/tenor-frame.css', 'tenor-frame.css'],
  ['picker/picker.html', 'picker.html'],
  ['picker/picker.css', 'picker.css'],
  ['offscreen/offscreen.html', 'offscreen.html'],
];

function copyStatic() {
  mkdirSync(dist, { recursive: true });
  for (const [from, to] of STATIC_FILES) {
    const source = join(src, from);
    if (!existsSync(source)) throw new Error(`missing static file: ${source}`);
    copyFileSync(source, join(dist, to));
  }
}

/**
 * Fail the build if the manifest points at something we did not emit. Catching
 * this here beats discovering it as a silent no-op after loading unpacked.
 */
function verifyManifest() {
  const manifest = JSON.parse(readFileSync(join(dist, 'manifest.json'), 'utf8'));
  const referenced = new Set();

  const add = (value) => {
    if (typeof value === 'string' && /\.(js|css|html|png)$/.test(value)) referenced.add(value);
  };
  const walk = (node) => {
    if (Array.isArray(node)) node.forEach(walk);
    else if (node && typeof node === 'object') Object.values(node).forEach(walk);
    else add(node);
  };
  walk(manifest);

  const missing = [...referenced].filter((file) => !existsSync(join(dist, file)));
  if (missing.length > 0) {
    throw new Error(`manifest references files that were not built:\n  ${missing.join('\n  ')}`);
  }
  return referenced.size;
}

const options = {
  entryPoints: ENTRIES,
  outdir: dist,
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: ['chrome116'],
  sourcemap: dev ? 'inline' : false,
  minify: !dev,
  legalComments: 'none',
  logLevel: 'info',
};

async function build() {
  rmSync(dist, { recursive: true, force: true });
  copyStatic();
  const icons = writeIcons(join(dist, 'icons'));
  await esbuild.build(options);
  const count = verifyManifest();
  console.log(
    `✓ built ${Object.keys(ENTRIES).length} bundles, ${STATIC_FILES.length} static files, ` +
      `${icons.length} icons — ${count} manifest references verified`,
  );
  console.log(`  load unpacked from: ${resolve(dist)}`);
}

if (watch) {
  rmSync(dist, { recursive: true, force: true });
  copyStatic();
  writeIcons(join(dist, 'icons'));
  const ctx = await esbuild.context(options);
  await ctx.watch();
  console.log('watching for changes…');
} else {
  await build();
}
